### ISSUE TITLE
[AuthEasy] Class Not Found

### ISSUE THREAD

**Issue by remotevase** [remotevase/ImagicalMine-Plugins#1]
`[CRITICAL]: ClassNotFoundExeption: "Class AuthEasy\common\mc not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

**Comment by Taki21** [comment]
Hm dats strange ... il see the repo

**Comment by Taki21** [comment]
where is common foldeR?

**Comment by Taki21** [comment]
without common folder....everything messed up! And also there were files that should have been in the common folder!!! xD

**Comment by remotevase** [comment]
oh! I didnt know why I needed common folder

**Comment by remotevase** [comment]
which files?

**Comment by Taki21** [comment]
idk i think you should remove the class names with: common

**Comment by TheDragonRing** [comment]
That would probably help

**Comment by remotevase** [comment]
umm. ok, that would probably help, but IDK if it would remove some features...

**Comment by remotevase** [comment]
fixed

**Comment by Taki21** [comment]
XD

**Comment by remotevase** [comment]
Oh, lol forgot to do that
